"""Case management service with status transitions and assignment logic."""

from __future__ import annotations

from datetime import date, datetime, timezone
from uuid import UUID

from fastapi import HTTPException, status
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.constants import CaseStatus, CaseType, Priority
from app.core.pagination import PaginatedResponse, PaginationParams, paginate
from app.models.case import Case, CaseAssignment, CaseHistory, CaseNote
from app.models.client import Client
from app.models.user import User
from app.schemas.case import (
    ALLOWED_TRANSITIONS,
    CaseAssignRequest,
    CaseCreate,
    CaseHistoryRead,
    CaseNoteCreate,
    CaseNoteRead,
    CaseRead,
    CaseStatusTransition,
    CaseUpdate,
)
from app.schemas.case import CaseStatus as SchemaCaseStatus


async def _get_case_or_404(session: AsyncSession, case_id: UUID) -> Case:
    result = await session.execute(
        select(Case).where(Case.id == case_id, Case.is_deleted == False)
    )
    case = result.scalar_one_or_none()
    if case is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case not found")
    return case


async def _build_case_read(session: AsyncSession, case: Case) -> CaseRead:
    client_name = None
    if case.client:
        client_name = case.client.full_name
    elif case.client_id:
        cr = await session.execute(select(Client).where(Client.id == case.client_id))
        client = cr.scalar_one_or_none()
        if client:
            client_name = client.full_name

    assigned_name = None
    if case.assigned_to:
        assigned_name = case.assigned_to.full_name

    return CaseRead(
        id=case.id,
        case_number=str(case.case_number),
        client_id=case.client_id,
        client_name=client_name,
        case_type=case.case_type.value,
        title=f"Case #{case.case_number}",
        description=case.description,
        status=case.status.value,
        priority=case.priority.value,
        assigned_to=case.assigned_to_id,
        assigned_to_name=assigned_name,
        due_date=datetime.combine(case.due_date, datetime.min.time()) if case.due_date else None,
        closed_at=datetime.combine(case.closed_date, datetime.min.time()) if case.closed_date else None,
        created_at=case.created_at,
        updated_at=case.updated_at,
    )


async def _record_history(
    session: AsyncSession,
    case_id: UUID,
    user_id: UUID | None,
    field_name: str,
    old_value: str | None = None,
    new_value: str | None = None,
    change_reason: str | None = None,
) -> None:
    """Write an audit entry to case_history."""
    history = CaseHistory(
        case_id=case_id,
        changed_by_id=user_id,
        field_name=field_name,
        old_value=old_value,
        new_value=new_value,
        change_reason=change_reason,
    )
    session.add(history)


async def create_case(
    session: AsyncSession, payload: CaseCreate, created_by: UUID
) -> CaseRead:
    """Create a new case. case_number is auto-generated by the DB sequence."""
    # Verify client exists
    client_result = await session.execute(
        select(Client).where(Client.id == payload.client_id, Client.is_deleted == False)
    )
    if client_result.scalar_one_or_none() is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Client not found")

    case = Case(
        client_id=payload.client_id,
        case_type=CaseType(payload.case_type.value),
        description=payload.description,
        status=CaseStatus.INTAKE,
        priority=Priority(payload.priority.value),
        assigned_to_id=payload.assigned_to,
        due_date=payload.due_date.date() if payload.due_date else None,
        opened_date=date.today(),
    )
    session.add(case)
    await session.flush()
    await session.refresh(case)

    await _record_history(session, case.id, created_by, "status", new_value="intake", change_reason="Case created")

    return await _build_case_read(session, case)


async def get_case(session: AsyncSession, case_id: UUID) -> CaseRead:
    """Get a case by ID."""
    case = await _get_case_or_404(session, case_id)
    return await _build_case_read(session, case)


async def list_cases(
    session: AsyncSession, pagination: PaginationParams, **filters
) -> PaginatedResponse[CaseRead]:
    """List cases with optional filters."""
    query = select(Case).where(Case.is_deleted == False)

    if filters.get("client_id"):
        query = query.where(Case.client_id == filters["client_id"])
    if filters.get("status"):
        query = query.where(Case.status == filters["status"])
    if filters.get("case_type"):
        query = query.where(Case.case_type == filters["case_type"])
    if filters.get("assigned_to"):
        query = query.where(Case.assigned_to_id == filters["assigned_to"])
    if filters.get("priority"):
        query = query.where(Case.priority == filters["priority"])

    query = query.order_by(Case.created_at.desc())
    return await paginate(session, query, pagination, CaseRead)


async def update_case(
    session: AsyncSession, case_id: UUID, payload: CaseUpdate, updated_by: UUID
) -> CaseRead:
    """Update case fields (not status -- use transition_status for that)."""
    case = await _get_case_or_404(session, case_id)

    update_data = payload.model_dump(exclude_unset=True)
    for field, value in update_data.items():
        old_val = str(getattr(case, field, None))
        if hasattr(value, "value"):
            value = value.value
        if field == "priority":
            setattr(case, field, Priority(value))
        elif field == "case_type":
            setattr(case, field, CaseType(value))
        elif field == "due_date" and value is not None:
            case.due_date = value.date() if hasattr(value, "date") else value
        else:
            setattr(case, field, value)
        await _record_history(
            session, case.id, updated_by, field, old_value=old_val, new_value=str(value),
        )

    session.add(case)
    await session.flush()
    return await _build_case_read(session, case)


async def delete_case(session: AsyncSession, case_id: UUID, deleted_by: UUID) -> None:
    """Soft-delete a case."""
    case = await _get_case_or_404(session, case_id)
    case.is_deleted = True
    case.deleted_at = datetime.now(timezone.utc)
    session.add(case)
    await _record_history(session, case.id, deleted_by, "is_deleted", old_value="False", new_value="True")


async def transition_status(
    session: AsyncSession,
    case_id: UUID,
    payload: CaseStatusTransition,
    user_id: UUID,
) -> CaseRead:
    """Transition a case to a new status, validating the transition is allowed."""
    case = await _get_case_or_404(session, case_id)

    current = SchemaCaseStatus(case.status.value)
    new = payload.new_status
    allowed = ALLOWED_TRANSITIONS.get(current, [])

    if new not in allowed:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Transition from '{current.value}' to '{new.value}' is not allowed. "
                   f"Allowed: {[s.value for s in allowed]}",
        )

    old_status = case.status.value
    case.status = CaseStatus(new.value)

    if new.value in ("closed", "archived", "closed_successful", "closed_unsuccessful", "closed_withdrawn"):
        case.closed_date = date.today()

    session.add(case)
    await _record_history(
        session, case.id, user_id, "status", old_value=old_status, new_value=new.value,
        change_reason=payload.reason,
    )

    return await _build_case_read(session, case)


async def assign_staff(
    session: AsyncSession, case_id: UUID, payload: CaseAssignRequest, assigned_by: UUID
) -> CaseRead:
    """Assign or reassign a case to a staff member."""
    case = await _get_case_or_404(session, case_id)

    staff_result = await session.execute(
        select(User).where(User.id == payload.assigned_to, User.is_active == True)
    )
    if staff_result.scalar_one_or_none() is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Staff user not found or inactive"
        )

    old_assigned = str(case.assigned_to_id) if case.assigned_to_id else None
    case.assigned_to_id = payload.assigned_to
    session.add(case)

    # Record assignment
    assignment = CaseAssignment(
        case_id=case.id,
        user_id=payload.assigned_to,
        assigned_by_id=assigned_by,
        is_primary=True,
        assigned_at=datetime.now(timezone.utc),
    )
    session.add(assignment)

    await _record_history(
        session, case.id, assigned_by, "assigned_to_id",
        old_value=old_assigned, new_value=str(payload.assigned_to),
        change_reason=payload.note,
    )

    if payload.note:
        note = CaseNote(
            case_id=case.id,
            author_id=assigned_by,
            content=f"Assignment note: {payload.note}",
            is_private=True,
        )
        session.add(note)

    await session.flush()
    return await _build_case_read(session, case)


# --- Notes ---

async def add_note(
    session: AsyncSession, case_id: UUID, payload: CaseNoteCreate, author_id: UUID
) -> CaseNoteRead:
    """Add a note to a case."""
    await _get_case_or_404(session, case_id)

    note = CaseNote(
        case_id=case_id,
        author_id=author_id,
        content=payload.content,
        is_private=payload.is_internal,
    )
    session.add(note)
    await session.flush()
    await session.refresh(note)

    author_name = note.author.full_name if note.author else None

    return CaseNoteRead(
        id=note.id,
        case_id=note.case_id,
        author_id=note.author_id,
        author_name=author_name,
        content=note.content,
        is_internal=note.is_private,
        created_at=note.created_at,
        updated_at=note.updated_at,
    )


async def list_notes(
    session: AsyncSession, case_id: UUID, pagination: PaginationParams
) -> PaginatedResponse[CaseNoteRead]:
    """List notes for a case."""
    await _get_case_or_404(session, case_id)
    query = (
        select(CaseNote)
        .where(CaseNote.case_id == case_id)
        .order_by(CaseNote.created_at.desc())
    )
    return await paginate(session, query, pagination, CaseNoteRead)


async def get_history(
    session: AsyncSession, case_id: UUID, pagination: PaginationParams
) -> PaginatedResponse[CaseHistoryRead]:
    """Get the audit history for a case."""
    await _get_case_or_404(session, case_id)
    query = (
        select(CaseHistory)
        .where(CaseHistory.case_id == case_id)
        .order_by(CaseHistory.created_at.desc())
    )
    return await paginate(session, query, pagination, CaseHistoryRead)
